#version: 'v2.32.1'

services:
  sitetablica:
    # Берем Dockerfile из каталога app
    build: .
    command: python manage.py makemigrations
    command: python manage.py migrate
    # Запускаем тестовый сервер
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    # куда будут помещены данные из каталога app
    volumes:
      - .:/app
    # Открываем порт 8000 внутри и снаружи
    ports:
      - 8000:8000
    # Файл содержащий переменные для контейнера
    env_file:
      - .env
