# Generated by Django 5.1.4 on 2025-01-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_post_options_post_enabled_alter_post_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Отображать'),
        ),
    ]
