# Generated by Django 5.1.4 on 2025-01-14 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_post_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(blank=True, max_length=100, verbose_name='Темаэ')),
                ('nick', models.CharField(blank=True, max_length=100, verbose_name='Ник')),
                ('description', models.CharField(blank=True, max_length=2000, verbose_name='Описание')),
                ('logo', models.ImageField(blank=True, upload_to='image/', verbose_name='Логотип')),
                ('background', models.ImageField(blank=True, upload_to='image/', verbose_name='Фон страницы')),
                ('enabled', models.BooleanField(default=True, verbose_name='Установить настройки')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Настройки',
            },
        ),
    ]
