# Generated by Django 5.1.4 on 2025-01-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
