# Generated by Django 5.1.4 on 2025-01-14 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_settings_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='background',
            field=models.ImageField(blank=True, upload_to='backgrounds/', verbose_name='Фон страницы'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='logo',
            field=models.ImageField(blank=True, upload_to='logos/', verbose_name='Логотип'),
        ),
    ]
