# Generated by Django 5.1.4 on 2025-01-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_settings_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, verbose_name='Стоимость')),
                ('enabled', models.BooleanField(default=True, verbose_name='Показывать на странице')),
            ],
        ),
        migrations.DeleteModel(
            name='Price',
        ),
    ]
