# Generated by Django 5.1.4 on 2025-01-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_prices_servise_alter_servise_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servise',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, verbose_name='Стоимость'),
        ),
    ]
