# Generated by Django 5.1.4 on 2025-01-21 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_socials_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='socials',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название'),
        ),
    ]
